version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=devarshi
      - POSTGRES_PASSWORD=devarshi
      - POSTGRES_DB=app
    volumes:
      - pg_v:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=devarshi.trivedi@improwised.com
      - PGADMIN_DEFAULT_PASSWORD=k@k.k
    ports:
      - "8080:80"

volumes:
  pg_v:
